# custom JetBrains Rider properties

idea.config.path=$HOME/.config/Jetbrains/Rider/config
idea.system.path=$HOME/.config/Jetbrains/Rider/system
idea.plugins.path=$HOME/.config/Jetbrains/Rider/plugins