#!/bin/sh

# ls
alias ls='exa'
alias ll='exa -Fhlg --group-directories-first'
alias la='exa -Fhalg --group-directories-first'

# git
alias g='git'
alias gbm='g br --merged | rg -v "(^\*|master)" | xargs g brd'

# docker
alias d='docker'

# docker-compose
alias dc='docker-compose'
alias dcu='dc up -d --build --remove-orphans'
alias dcul='dcu -f docker-compose.local-develop.yml'
alias dcs='dc stop'
alias dcd='dc down'
alias dcde='dc down && exit'

# get fastest mirrors
alias mirror='sudo reflector -f 30 -l 30 --number 10 -p "https,rsync" -c US --verbose --save /etc/pacman.d/mirrorlist'

# colorize grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

# confirm before overwriting
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# human readable sizes
alias df='df -h'
alias free='free -m'

# XDG stuff
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias wget='wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts'
