#!/bin/sh

# ls
alias ll='ls -lh --color=auto'
alias la='ls -lAh --color=auto'

# git
alias gst='git status'
alias ga='git add'
alias gc='git checkout'
alias gds="git diff --staged"
alias gp="git pull -p"

# docker-compose
alias dcu='docker-compose up -d --build --remove-orphans'
alias dcul='docker-compose -f docker-compose.local-develop.yml up -d --build'
alias dcs='docker-compose stop'
alias dcd='docker-compose down'
alias dcde='docker-compose down && exit'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --country US --verbose --save /etc/pacman.d/mirrorlist"

# colorize grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

# confirm before overwriting
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# human readable sizes
alias df='df -h'
alias free='free -m'

# XDG stuff
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias wget='wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts'
