#!/bin/sh

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XMONAD_CONFIG_DIR=$HOME/.config/xmonad/

export ZDOTDIR=$HOME/.config/zsh
