#!/bin/sh

export HISTSIZE=1000000
export SAVEHIST=1000000

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
# export XDG_CURRENT_DESKTOP=sway
# export XDG_RUNTIME_DIR=$HOME/.run

export XMONAD_CONFIG_DIR=$HOME/.config/xmonad/
# export WLR_DRM_DEVICES=/dev/dri/card0

export ZDOTDIR=$HOME/.config/zsh
export HISTFILE="$XDG_STATE_HOME"/zsh/history

export BAT_THEME=OneHalfDark
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml

export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

export NUGET_PACKAGES="$XDG_CONFIG_HOME"/NuGetPackages
export WGETRC="$XDG_CONFIG_HOME"/wgetrc
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export KODI_DATA="$XDG_DATA_HOME"/kodi
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export STACK_ROOT="$XDG_DATA_HOME"/stack
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
export CONAN_USER_HOME="$XDG_CONFIG_HOME"

export DOTNET_CLI_TELEMETRY_OPTOUT=1

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export GOPATH="$XDG_DATA_HOME"/go

export PATH=$HOME/.local/bin:$HOME/.local/share/cargo/bin:$HOME/.ghcup/bin:$GOPATH/bin:$PATH
