- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
  tags:
    - install_aur

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  tags:
    - install_aur

- name: Install yay
  kewlfft.aur.aur:
    use: makepkg
    name: yay
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - install_aur
