#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	4
bspc config window_gap           	24
bspc config top_padding			16

bspc config split_ratio          	0.5
bspc config borderless_monocle  	false
bspc config gapless_monocle     	false
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#1d2021"
bspc config focused_border_color	"#3c3836"
bspc config presel_feedback_color	"#3c3836"

bspc rule -a feh state=floating

# start bar
~/.config/polybar/launch.sh
