# backend
backend = "glx";
glx-no-rebind-pixmap = true;
glx-no-stencil = true;
unredir-if-possible = false;
vsync = "opengl-swc";
xrenxder-sync = true;
xrender-sync-fence = true;

# fading
fading = true;
fade-delta = 3;
no-fading-openclose = true;

# shadows
shadow = true;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.3;
shadow-radius = 6;
shadow-exclude = [
  "class_g ?= 'Plank'"
];

blur-background = false;
blur-kern = "7,7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
